import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NavBar } from "./components/navBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Boost Lobby",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{
					<div className="h-screen w-screen">
						<NavBar />
						{children}
					</div>
				}
			</body>
		</html>
	);
}
